// filename: TestRunner.java
// Code Generated by Sidekick is for learning and experimentation purposes only.

package runners;

import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;

@CucumberOptions(
        features  = "src/test/resources/Features",          // path to .feature files
        glue      = {"hooks", "stepdefinitions"},            // step defs + hooks packages
        plugin    = {
                "pretty",                                        // readable console output
                "html:reports/cucumber-html-report.html",        // built-in Cucumber HTML
                "json:reports/cucumber.json"                     // JSON for CI integration
        },
        monochrome = true,                                    // clean console output
        tags = "@test"
)
public class TestRunner extends AbstractTestNGCucumberTests {
    // Inherits all Cucumber-TestNG wiring from AbstractTestNGCucumberTests
}
