// filename: CucumberHooks.java
// Code Generated by Sidekick is for learning and experimentation purposes only.

package hooks;

import io.cucumber.java.After;
import io.cucumber.java.Before;
import io.cucumber.java.Scenario;
import org.example.BaseTest;
import org.example.ExtentReportManager;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;

public class CucumberHooks {

    // ── Runs before every Scenario ────────────────────────────────
    @Before
    public void setUp(Scenario scenario) {
        // Start WebDriver and navigate to URL
        BaseTest.initDriver();

        // Create an ExtentTest entry for this scenario
        ExtentReportManager.createTest(scenario.getName());
        ExtentReportManager.getTest().info("▶ Starting: " + scenario.getName());
    }

    // ── Runs after every Scenario ─────────────────────────────────
    @After
    public void tearDown(Scenario scenario) {

        // Capture screenshot on failure
        if (scenario.isFailed()) {
            byte[] screenshot = ((TakesScreenshot) BaseTest.driver)
                    .getScreenshotAs(OutputType.BYTES);
            scenario.attach(screenshot, "image/png", "Failure Screenshot");
            ExtentReportManager.getTest().fail("❌ Scenario FAILED: " + scenario.getName());
        } else {
            ExtentReportManager.getTest().pass("✅ Scenario PASSED: " + scenario.getName());
        }

        // Flush report and quit driver
        ExtentReportManager.flushReport();
        BaseTest.quitDriver();
    }
}
