// filename: AccountRegistrationStepDefs.java
// Code Generated by Sidekick is for learning and experimentation purposes only.

package stepdefinitions;

import io.cucumber.java.en.*;
import org.example.BaseTest;
import org.example.ExtentReportManager;
import pages.AccountRegistrationPage;

public class AccountRegistrationStepDefs extends BaseTest {

    AccountRegistrationPage registrationPage = new AccountRegistrationPage();

    @Given("I navigate to the registration page")
    public void iNavigateToTheRegistrationPage() {
        ExtentReportManager.getTest().info("📌 Step: Given I navigate to the registration page");
        registrationPage.navigateToRegistrationPage();
    }

    @When("I fill in the registration form")
    public void iFillInTheRegistrationForm() {
        ExtentReportManager.getTest().info("📌 Step: When I fill in the registration form");
        registrationPage.enterFirstName();
        registrationPage.enterLastName();
        registrationPage.enterEmail();
        registrationPage.enterPhoneNumber();
        registrationPage.selectOccupation();
        registrationPage.selectGender();
        registrationPage.enterPassword();
        registrationPage.enterConfirmPassword();
        registrationPage.clickTermsCheckbox();
        ExtentReportManager.getTest().pass("Registration Form Filled");
    }

    @And("I submit the form")
    public void iSubmitTheForm() {
        ExtentReportManager.getTest().info("📌 Step: And I submit the form");
        registrationPage.clickRegisterButton();
    }

    @Then("I should be registered successfully")
    public void iShouldBeRegisteredSuccessfully() {
        ExtentReportManager.getTest().info("📌 Step: Then I should be registered successfully");
        registrationPage.verifySuccessMessage();
        ExtentReportManager.getTest().pass("✅ Registration successful!");
    }

    @When("a user is already registered and attempts to register himself")
    public void fillInTheForm() {
        ExtentReportManager.getTest().info("📌 Step: Given I navigate to the registration page");
        registrationPage.navigateToRegistrationPage();
        iFillInTheRegistrationForm();
        registrationPage.clickRegisterButton();
        ExtentReportManager.getTest().pass("✅ Register button clicked after filling the form!");
    }

    @Then("an error message saying user already exists displays")
    public void userExistsErrorMessage() {
        ExtentReportManager.getTest().info("user Exists error message should be displayed");
        registrationPage.verifyUserExistMessage();
        ExtentReportManager.getTest().pass("user Exists error message is displayed");
    }

    @When("I submit the form without filling any fields")
    public void iSubmitTheFormWithoutFillingAnyFields() {
        ExtentReportManager.getTest().info("Submitting the form with all the fields empty");
        registrationPage.clickRegisterButton();
        ExtentReportManager.getTest().pass("Form Submitted");
    }

    @Then("mandatory field validation errors should be displayed")
    public void mandatoryFieldValidationErrorsShouldBeDisplayed() {
        ExtentReportManager.getTest().info("Mandatory field validation errors should be displayed");
        registrationPage.validateBlankFirstNameErrorMsg();
        registrationPage.validateBlankEmailErrorMsg();
        registrationPage.validateBlankPhnNoErrorMsg();
        registrationPage.validateBlankPasswordErrorMsg();
        registrationPage.validateBlankCheckBoxErrorMsg();
        ExtentReportManager.getTest().pass("Mandatory field validation errors are displayed");
    }

}
