# filename: UserLogin.feature
# Code Generated by Sidekick is for learning and experimentation purposes only.

Feature: User Login on LetsShop

  # SCENARIO 1 — POSITIVE: Successful Login
  @Positive @Regression
  Scenario: Successfully login with valid credentials
    Given I am on the login page
    When I enter a valid registered email and password
    And I click the login button
    Then I should be redirected to the dashboard successfully

  # SCENARIO 2 — NEGATIVE: Wrong Password
  @Negative @Regression
  Scenario: Verify error message when login is attempted with a wrong password
    Given I am on the login page
    When I enter a valid registered email and an incorrect password "WrongPass@99"
    And I click the login button
    Then an error message saying "Incorrect email or password." should be displayed

  # SCENARIO 3 — NEGATIVE: Unregistered Email
  @Negative @Regression
  Scenario: Verify error message when login is attempted with an unregistered email
    Given I am on the login page
    When I enter an unregistered email "notregistered@test.com" and a password "Test@1234"
    And I click the login button
    Then an error message saying "Incorrect email or password." should be displayed

  # SCENARIO 4 — NEGATIVE: Invalid Email Format
  @Negative @Regression
  Scenario: Verify error when an invalid email format is entered on the login page
    Given I am on the login page
    When I enter an invalid email format "johndoe@" and a password "Test@1234"
    And I click the login button
    Then an email format validation error should be displayed on login page

  # SCENARIO 5 — NEGATIVE: Empty Form Submission
  @Negative @Regression
  Scenario: Verify validation errors when login form is submitted empty
    Given I am on the login page
    When I click the login button without entering any credentials
    Then mandatory field validation errors should be displayed on login page

  # SCENARIO 6 — POSITIVE: Navigate to Registration from Login page
  @Positive @Regression
  Scenario: Verify user is navigated to the registration page from the login page
    Given I am on the login page
    When I click on the Register link
    Then I should be navigated to the registration page
